### ISSUE TITLE
i2c dead lock

### ISSUE THREAD

**Issue by watershade** [Seeed-Studio/Grove_I2C_Motor_Driver_v1_3#11]
It is easy to generate deaklock because grove use i2c bus. (When you reset host, bust i2c is communiting with each other.)
In case of this I suggest to add code in it:
`
  // prevent i2c deadlock
  pinMode(SCL,OUTPUT);
  for(int i = 0; i<9; i++){
    digitalWrite(SCL, HIGH);
    delayMicroseconds(2);
    digitalWrite(SCL, LOW);
    delayMicroseconds(2);
  }`

Add you should add some notes on your wiki. To tell user: begin,speed,stop can not be call in ISR.
And your code will change the bardrate of Serial to 9600. And it is also need to remind users about it.

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
