### ISSUE TITLE
I2C unstable

### ISSUE THREAD

**Issue by eddie4** [Seeed-Studio/Grove_I2C_Motor_Driver_v1_3#2]
Hello,

Am using Grove I2C Motor Driver v1_3 to control  a few motors in combination with a raspberry pi.  When using the command i2cdetect -y 1. However when doing this the first time it will correctly list the address 0f. Doing this a second, 3th or 100th time will result in no results. When pressing reset button on the motor driver you will be able to detect it once. 

**First boot or after reset**
root@raspberrypi: i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- 0f
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

**After doing the first detect**
root@raspberrypi: i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

Also there are 3 other devices connected to the I2C bus these are not detected at all when motor driver is connected but are when it's disconnected. Above issue occurred with and without other I2C devices connected.  

**When disconnecting I2C Motor Driver v1_3**
root@raspberrypi: i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- 27 -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- 49 -- -- 4c -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

I am able to control the chip if i never do a detect or try to talk to the other devices. 

EDIT:
Removing the jumper for using a different powersource doesn't not fix the problem.

**Comment by Pillar1989** [comment]
@eddie4  Do you modify  Grove_I2C_Motor_Driver_v1_3 firmware ?

**Comment by eddie4** [comment]
No,  I didn't touch the firmware. This is what i got out of the box. You weren't able to reproduce the issue?

**Comment by lanselambor** [comment]
@eddie4 This problem has been fixed at the new firmware. Please refer to https://github.com/Seeed-Studio/Grove_I2C_Motor_Driver/issues/1

**Comment by eddie4** [comment]
AWESOME!!!!
