### ISSUE TITLE
Serial speed

### ISSUE THREAD

**Issue by tchapi** [Seeed-Studio/Grove_I2C_Motor_Driver_v1_3#6]
Hello,

Why starting the Serial port in the `begin()` method ? It prevents any other parts of the code to use the Serial at a different speed, and locks the serial monitor (since there is a change of speed mid-program).

The library should not init `Serial`, but rather assume that it's present (just like in the DHT library for instance : https://github.com/Seeed-Studio/Grove_Temperature_And_Humidity_Sensor)

**Comment by tchapi** [comment]
A correct fix would just need to remove this line : 
https://github.com/Seeed-Studio/Grove_I2C_Motor_Driver_v1_3/blob/master/Grove_I2C_Motor_Driver.cpp#L46

**Comment by akita11** [comment]
There are other lines that use Serial. I think the use of Serial should be selectable by user, such as using #define. It would be used for debugging, not for normal use. The error would be checked by the return value of functions.

**Comment by lanselambor** [comment]
@tchapi @akita11 We only need to move __Serial.begin(9600);__ to the __ino__ files.

**Comment by tchapi** [comment]
That's exactly what I'm talking about @lanselambor 👍

**Comment by tchapi** [comment]
Thanks a lot !
