### ISSUE TITLE
Support multiple Motor Drivers

### ISSUE THREAD

**Issue by SohnyBohny** [Seeed-Studio/Grove_I2C_Motor_Driver_v1_3#9]
Is it possible to use multiple motor drivers with one Arduino?
Every motor driver can have an individual i2c address, but there is no possibility to create multiple objects of `I2CMotorDriver` class with different i2c addresses.

**Comment by lanselambor** [comment]
@SohnyBohny the method  __I2CMotorDriver::begin(unsigned char i2c_add)__ can help create a different i2c address for the new object.

**Comment by SohnyBohny** [comment]
Perfect - thank you :smiley:
Maybe a constructor could be added to make this more  intuitive.
